name: Selenium testing automation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-automation-test:

    runs-on: ubuntu-latest

    steps:
    # download repo
    - uses: actions/checkout@v3

    # Setup Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    # Install Chrome browser
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0

    # Setup Gradlew
    - name: Setup Gradlew
      run: chmod +x gradlew

    # Execute graddle command for running cucumber test
    - name: Execute Test
      run: ./gradlew cucumber

    # Archive Test Result
    - name: Archive Test Result
      uses: actions/upload-artifact@v4.0.0
      if: always()
      with:
        name: Cucumber Report
        path: reports
     
    # Deploy to Github Pages
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with: 
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports
